networks:
  trustification:

volumes:
  postgres-data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TRUSTD_DB_HOST: db
      HTTP_SERVER_BIND_ADDR: "::" # Required to disable IPv6
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - trustification
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - trustification
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
